# Generated by Django 5.1.3 on 2024-12-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_artist_genre_album_track'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Артист', 'verbose_name_plural': 'Артисты'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
