# Generated by Django 5.1.3 on 2025-01-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
